[project]
name = "pt750"
dynamic = ["version"]
description = "label printing tools for brother PT-P750W label maker"
authors = [{ name = "rpedde", email = "ron@pedde.com" }]
requires-python = ">=3.10,<4.0"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "Pillow",
    "treepoem",
    "fastapi[all]",
    "Jinja2",
    "uvicorn",
    "PyYAML",
    "easysnmp",
    "opencv-python",
    "httpx",
    "pydantic-settings",
]

[project.scripts]
makelabel = "pt750.main:main"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true }}]

[dependency-groups]
dev = [
    "pytest",
    "mypy",
    "jsf",
    "requests",
    "ruff",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.hooks.version]
path = "pt750/_version.py"
template = '''
__version__ = "{version}"
'''

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = ["E", "F", "I", "C90"]
