name: pre-commit and unit tests

on:
  push:
    branches-ignore:
      - "master"

jobs:
  unit-test:
    name: unit-test code base
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: install uv
        uses: astral-sh/setup-uv@v7

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: install apt-packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - name: install deps
        run: uv sync --locked --all-extras --dev

      - name: run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: run tests
        run: uv run pytest -vvv
